### ISSUE TITLE
hsluv batch

### ISSUE THREAD

**Issue by JojoIce** [tommyettinger/colorful-gdx#3]
New to this lib, so I do not know what I am doing, but the following:
`new com.github.tommyettinger.colorful.hsluv.ColorfulBatch();`
result in this:
```
Exception in thread "main" java.lang.IllegalArgumentException: Error compiling shader: Vertex shader
ERROR: 0:33: '*' does not operate on 'float' and 'int'
ERROR: 0:46: '*' does not operate on 'float' and 'int'
ERROR: 0:59: '*' does not operate on 'float' and 'int'
Fragment shader:
ERROR: 0:49: '*' does not operate on 'float' and 'int'
ERROR: 0:62: '*' does not operate on 'float' and 'int'
ERROR: 0:75: '*' does not operate on 'float' and 'int'

	at com.github.tommyettinger.colorful.hsluv.ColorfulBatch.createDefaultShader(ColorfulBatch.java:472)
	at com.github.tommyettinger.colorful.hsluv.ColorfulBatch.<init>(ColorfulBatch.java:131)
	at com.github.tommyettinger.colorful.hsluv.ColorfulBatch.<init>(ColorfulBatch.java:84)
```
Any other colorspace seems to initiate fine.

Colorful 0.8.1 and gdx 1.10.0 on Mac and lwjgl3 or lwjgl2 (only ones tested). Not sure what I could have messed up at this point so it might be a bug.

**Comment by tommyettinger** [comment]
Well, it's probably some ridiculously simple mistake I made, like omitting a `.0` after a number. The line numbers help, I'll investigate now.

**Comment by tommyettinger** [comment]
Yeah this is mostly some .0 missing after some numbers in the shaders... but... those shaders use the older HUSL color space, a precursor to HSLuv. When I update to the HSLuv shaders, everything breaks in mysterious ways. ColorTools uses HSLuv in I think the right way. So, for now the current commit should work, but it's still going to be updated, if I can, to HSLuv in the shaders at some point. I'll leave this open until I either figure out HSLuv in the shaders or go insane trying to match dozens of different numbers so they are just right.

**Comment by tommyettinger** [comment]
OK, this should be fixed now, and probably has been for a while... I don't use HSLuv much, to be honest, though it has some nice properties for sure.
